/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/brain.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brain.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.freesurff3.geometry} material={nodes.freesurff3.material} rotation={[1.99, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/brain.glb')
